# docker-compose.yaml
version: "3"
services:
  frontend:
    image: webpack
    build:
      context: ./app
    ports:
      - 8080:8080
    volumes:
      - ./app:/bindmount:rw
      - node_modules:/src/node_modules
volumes:
  node_modules: